"use client";

// frontend/src/app/(app)/settings/page.tsx
// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes

import { useState, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useAuthStore } from "@/stores/authStore";
import apiClient from "@/lib/api";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import {
  User,
  Lock,
  Loader2,
  Eye,
  EyeOff,
  AlertCircle,
  CheckCircle2,
  Save,
} from "lucide-react";

// Password strength calculation helper
function calculatePasswordStrength(password: string): { score: number; label: string; color: string } {
  let score = 0;
  if (password.length >= 8) score += 25;
  if (password.length >= 12) score += 10;
  if (/[a-z]/.test(password)) score += 15;
  if (/[A-Z]/.test(password)) score += 15;
  if (/[0-9]/.test(password)) score += 15;
  if (/[^a-zA-Z0-9]/.test(password)) score += 20;

  if (score < 40) return { score, label: "Weak", color: "bg-red-500" };
  if (score < 70) return { score, label: "Fair", color: "bg-yellow-500" };
  if (score < 90) return { score, label: "Good", color: "bg-blue-500" };
  return { score, label: "Strong", color: "bg-green-500" };
}

export default function SettingsPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { user, mustChangePassword, setMustChangePassword } = useAuthStore();

  // Check for ?action=change-password query param
  const shouldExpandPasswordSection = searchParams.get("action") === "change-password" || mustChangePassword;

  // Profile form state
  const [displayName, setDisplayName] = useState(user?.full_name || "");
  const [isSavingProfile, setIsSavingProfile] = useState(false);
  const [profileError, setProfileError] = useState<string | null>(null);
  const [profileSuccess, setProfileSuccess] = useState(false);

  // Password form state
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showCurrentPassword, setShowCurrentPassword] = useState(false);
  const [showNewPassword, setShowNewPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [isChangingPassword, setIsChangingPassword] = useState(false);
  const [passwordError, setPasswordError] = useState<string | null>(null);
  const [passwordSuccess, setPasswordSuccess] = useState(false);

  // Password strength
  const passwordStrength = calculatePasswordStrength(newPassword);
  const passwordsMatch = newPassword === confirmPassword && confirmPassword.length > 0;

  // Update display name when user loads
  useEffect(() => {
    if (user?.full_name) {
      setDisplayName(user.full_name);
    }
  }, [user?.full_name]);

  // Handle profile save
  const handleSaveProfile = async (e: React.FormEvent) => {
    e.preventDefault();
    setProfileError(null);
    setProfileSuccess(false);
    setIsSavingProfile(true);

    try {
      const response = await apiClient.patch('/auth/me', { full_name: displayName });
      // Update auth store with new user data
      useAuthStore.getState().setUser({ ...user, full_name: displayName });
      setProfileSuccess(true);
    } catch (err) {
      setProfileError(err instanceof Error ? err.message : "Failed to update profile");
    } finally {
      setIsSavingProfile(false);
    }
  };

  // Handle password change
  const handleChangePassword = async (e: React.FormEvent) => {
    e.preventDefault();
    setPasswordError(null);
    setPasswordSuccess(false);

    // Validation
    if (newPassword.length < 8) {
      setPasswordError("New password must be at least 8 characters");
      return;
    }
    if (newPassword !== confirmPassword) {
      setPasswordError("Passwords do not match");
      return;
    }

    setIsChangingPassword(true);

    try {
      await apiClient.post('/auth/change-password', {
        current_password: currentPassword,
        new_password: newPassword
      });

      // Clear form
      setCurrentPassword("");
      setNewPassword("");
      setConfirmPassword("");

      // Clear must_change_password flag
      setMustChangePassword(false);
      setPasswordSuccess(true);

      // Redirect to chat after short delay
      setTimeout(() => {
        navigate("/chat");
      }, 1500);
    } catch (err) {
      setPasswordError(err instanceof Error ? err.message : "Failed to change password");
    } finally {
      setIsChangingPassword(false);
    }
  };

  // Get role badge variant
  const getRoleBadgeVariant = (role: string) => {
    switch (role) {
      case "superadmin":
        return "destructive";
      case "admin":
        return "default";
      case "member":
        return "secondary";
      default:
        return "outline";
    }
  };

  if (!user) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-auto p-4 sm:p-6 lg:p-8" role="main" aria-label="User settings">
      <div className="mx-auto max-w-2xl space-y-6">
        {/* Page Header */}
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Settings</h1>
          <p className="text-muted-foreground">Manage your profile and account security</p>
        </div>

        {/* Must Change Password Banner */}
        {mustChangePassword && (
          <div
            role="alert"
            aria-live="polite"
            className="flex items-start gap-3 rounded-lg border border-amber-200 bg-amber-50 p-4 text-amber-800"
          >
            <AlertCircle className="h-5 w-5 shrink-0 mt-0.5" aria-hidden="true" />
            <div>
              <p className="font-medium">Password Change Required</p>
              <p className="text-sm text-amber-700">
                You must change your password before continuing. Please update your password below.
              </p>
            </div>
          </div>
        )}

        {/* Profile Section */}
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <User className="h-5 w-5 text-muted-foreground" aria-hidden="true" />
              <CardTitle>Profile</CardTitle>
            </div>
            <CardDescription>Update your display name and view your account details</CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSaveProfile} className="space-y-4">
              {/* Success Message */}
              {profileSuccess && (
                <div
                  role="status"
                  aria-live="polite"
                  className="flex items-center gap-2 rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-800"
                >
                  <CheckCircle2 className="h-4 w-4" aria-hidden="true" />
                  <span>Profile updated successfully</span>
                </div>
              )}

              {/* Error Message */}
              {profileError && (
                <div
                  role="alert"
                  aria-live="polite"
                  className="flex items-start gap-2 rounded-lg border border-destructive/50 bg-destructive/10 p-3 text-sm text-destructive"
                >
                  <AlertCircle className="h-4 w-4 mt-0.5 shrink-0" aria-hidden="true" />
                  <span>{profileError}</span>
                </div>
              )}

              {/* Username (Read-only) */}
              <div className="space-y-2">
                <Label htmlFor="username">Username</Label>
                <Input
                  id="username"
                  type="text"
                  value={user.username}
                  disabled
                  aria-readonly="true"
                  className="bg-muted"
                />
                <p className="text-xs text-muted-foreground">Your username cannot be changed</p>
              </div>

              {/* Display Name (Editable) */}
              <div className="space-y-2">
                <Label htmlFor="displayName">Display Name</Label>
                <Input
                  id="displayName"
                  type="text"
                  value={displayName}
                  onChange={(e) => setDisplayName(e.target.value)}
                  placeholder="Enter your display name"
                  aria-label="Display name"
                  disabled={isSavingProfile}
                />
              </div>

              {/* Role Badge */}
              <div className="space-y-2">
                <Label>Role</Label>
                <div>
                  <Badge variant={getRoleBadgeVariant(user.role)} className="capitalize">
                    {user.role}
                  </Badge>
                </div>
              </div>

              {/* Save Button */}
              <div className="flex justify-end pt-2">
                <Button
                  type="submit"
                  disabled={isSavingProfile || displayName === user.full_name}
                  aria-busy={isSavingProfile}
                >
                  {isSavingProfile ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden="true" />
                      Saving...
                    </>
                  ) : (
                    <>
                      <Save className="mr-2 h-4 w-4" aria-hidden="true" />
                      Save Changes
                    </>
                  )}
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>

        {/* Change Password Section */}
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Lock className="h-5 w-5 text-muted-foreground" aria-hidden="true" />
              <CardTitle>Change Password</CardTitle>
            </div>
            <CardDescription>Update your password to keep your account secure</CardDescription>
          </CardHeader>
          <CardContent>
            <Accordion
              type="single"
              collapsible
              defaultValue={shouldExpandPasswordSection ? "password" : undefined}
              className="w-full"
            >
              <AccordionItem value="password" className="border-0">
                <AccordionTrigger className="py-0 hover:no-underline">
                  <span className="text-sm font-medium">Click to change password</span>
                </AccordionTrigger>
                <AccordionContent className="pt-4">
                  <form onSubmit={handleChangePassword} className="space-y-4">
                    {/* Success Message */}
                    {passwordSuccess && (
                      <div
                        role="status"
                        aria-live="polite"
                        className="flex items-center gap-2 rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-800"
                      >
                        <CheckCircle2 className="h-4 w-4" aria-hidden="true" />
                        <span>Password changed successfully. Redirecting...</span>
                      </div>
                    )}

                    {/* Error Message */}
                    {passwordError && (
                      <div
                        role="alert"
                        aria-live="polite"
                        className="flex items-start gap-2 rounded-lg border border-destructive/50 bg-destructive/10 p-3 text-sm text-destructive"
                      >
                        <AlertCircle className="h-4 w-4 mt-0.5 shrink-0" aria-hidden="true" />
                        <span>{passwordError}</span>
                      </div>
                    )}

                    {/* Current Password */}
                    <div className="space-y-2">
                      <Label htmlFor="currentPassword">Current Password</Label>
                      <div className="relative">
                        <Input
                          id="currentPassword"
                          type={showCurrentPassword ? "text" : "password"}
                          value={currentPassword}
                          onChange={(e) => setCurrentPassword(e.target.value)}
                          placeholder="Enter your current password"
                          aria-label="Current password"
                          autoComplete="current-password"
                          disabled={isChangingPassword}
                          className="pr-10"
                        />
                        <Button
                          type="button"
                          variant="ghost"
                          size="icon"
                          className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                          onClick={() => setShowCurrentPassword(!showCurrentPassword)}
                          disabled={isChangingPassword}
                          aria-label={showCurrentPassword ? "Hide current password" : "Show current password"}
                          aria-pressed={showCurrentPassword}
                        >
                          {showCurrentPassword ? (
                            <EyeOff className="h-4 w-4 text-muted-foreground" aria-hidden="true" />
                          ) : (
                            <Eye className="h-4 w-4 text-muted-foreground" aria-hidden="true" />
                          )}
                        </Button>
                      </div>
                    </div>

                    {/* New Password */}
                    <div className="space-y-2">
                      <Label htmlFor="newPassword">New Password</Label>
                      <div className="relative">
                        <Input
                          id="newPassword"
                          type={showNewPassword ? "text" : "password"}
                          value={newPassword}
                          onChange={(e) => setNewPassword(e.target.value)}
                          placeholder="Enter your new password"
                          aria-label="New password"
                          autoComplete="new-password"
                          disabled={isChangingPassword}
                          className="pr-10"
                        />
                        <Button
                          type="button"
                          variant="ghost"
                          size="icon"
                          className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                          onClick={() => setShowNewPassword(!showNewPassword)}
                          disabled={isChangingPassword}
                          aria-label={showNewPassword ? "Hide new password" : "Show new password"}
                          aria-pressed={showNewPassword}
                        >
                          {showNewPassword ? (
                            <EyeOff className="h-4 w-4 text-muted-foreground" aria-hidden="true" />
                          ) : (
                            <Eye className="h-4 w-4 text-muted-foreground" aria-hidden="true" />
                          )}
                        </Button>
                      </div>

                      {/* Password Strength Indicator */}
                      {newPassword.length > 0 && (
                        <div className="space-y-2 pt-1">
                          <div className="flex items-center justify-between text-xs">
                            <span className="text-muted-foreground">Password strength</span>
                            <span
                              className={`font-medium ${
                                passwordStrength.score < 40
                                  ? "text-red-500"
                                  : passwordStrength.score < 70
                                  ? "text-yellow-500"
                                  : passwordStrength.score < 90
                                  ? "text-blue-500"
                                  : "text-green-500"
                              }`}
                            >
                              {passwordStrength.label}
                            </span>
                          </div>
                          <Progress
                            value={passwordStrength.score}
                            className="h-2"
                            aria-label={`Password strength: ${passwordStrength.label}`}
                            aria-valuenow={passwordStrength.score}
                            aria-valuemin={0}
                            aria-valuemax={100}
                          >
                            <div
                              className={`h-full transition-all ${passwordStrength.color}`}
                              style={{ width: `${passwordStrength.score}%` }}
                            />
                          </Progress>
                          <ul className="text-xs text-muted-foreground space-y-1">
                            <li className={newPassword.length >= 8 ? "text-green-600" : ""}>
                              {newPassword.length >= 8 ? "✓" : "•"} At least 8 characters
                            </li>
                            <li className={/[A-Z]/.test(newPassword) ? "text-green-600" : ""}>
                              {/[A-Z]/.test(newPassword) ? "✓" : "•"} One uppercase letter
                            </li>
                            <li className={/[a-z]/.test(newPassword) ? "text-green-600" : ""}>
                              {/[a-z]/.test(newPassword) ? "✓" : "•"} One lowercase letter
                            </li>
                            <li className={/[0-9]/.test(newPassword) ? "text-green-600" : ""}>
                              {/[0-9]/.test(newPassword) ? "✓" : "•"} One number
                            </li>
                            <li className={/[^a-zA-Z0-9]/.test(newPassword) ? "text-green-600" : ""}>
                              {/[^a-zA-Z0-9]/.test(newPassword) ? "✓" : "•"} One special character
                            </li>
                          </ul>
                        </div>
                      )}
                    </div>

                    {/* Confirm Password */}
                    <div className="space-y-2">
                      <Label htmlFor="confirmPassword">Confirm New Password</Label>
                      <div className="relative">
                        <Input
                          id="confirmPassword"
                          type={showConfirmPassword ? "text" : "password"}
                          value={confirmPassword}
                          onChange={(e) => setConfirmPassword(e.target.value)}
                          placeholder="Confirm your new password"
                          aria-label="Confirm new password"
                          autoComplete="new-password"
                          disabled={isChangingPassword}
                          className={`pr-10 ${
                            confirmPassword && !passwordsMatch ? "border-destructive" : ""
                          }`}
                        />
                        <Button
                          type="button"
                          variant="ghost"
                          size="icon"
                          className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                          onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                          disabled={isChangingPassword}
                          aria-label={showConfirmPassword ? "Hide confirm password" : "Show confirm password"}
                          aria-pressed={showConfirmPassword}
                        >
                          {showConfirmPassword ? (
                            <EyeOff className="h-4 w-4 text-muted-foreground" aria-hidden="true" />
                          ) : (
                            <Eye className="h-4 w-4 text-muted-foreground" aria-hidden="true" />
                          )}
                        </Button>
                      </div>
                      {confirmPassword && !passwordsMatch && (
                        <p className="text-xs text-destructive">Passwords do not match</p>
                      )}
                    </div>

                    {/* Submit Button */}
                    <div className="flex justify-end pt-2">
                      <Button
                        type="submit"
                        disabled={
                          isChangingPassword ||
                          !currentPassword ||
                          !newPassword ||
                          !confirmPassword ||
                          !passwordsMatch ||
                          newPassword.length < 8
                        }
                        aria-busy={isChangingPassword}
                      >
                        {isChangingPassword ? (
                          <>
                            <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden="true" />
                            Changing Password...
                          </>
                        ) : (
                          "Change Password"
                        )}
                      </Button>
                    </div>
                  </form>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
