// frontend/src/app/(admin)/layout.tsx
// DESIGN SPEC — generated by Designer agent
// Coder: implement TODO items, do not change component structure or accessibility attributes

"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { Shield, Users, Lock, FolderOpen, ArrowLeft } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

interface AdminLayoutProps {
  children: React.ReactNode;
}

interface NavItem {
  href: string;
  label: string;
  icon: React.ReactNode;
}

const navItems: NavItem[] = [
  {
    href: "/admin/users",
    label: "Users",
    icon: <Users className="h-4 w-4" />,
  },
  {
    href: "/admin/groups",
    label: "Groups",
    icon: <Lock className="h-4 w-4" />,
  },
  {
    href: "/admin/vaults",
    label: "Vaults",
    icon: <FolderOpen className="h-4 w-4" />,
  },
];

function Breadcrumb() {
  const pathname = usePathname();
  const segments = pathname.split("/").filter(Boolean);

  return (
    <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-sm">
      <Link
        href="/admin"
        className="text-muted-foreground hover:text-foreground transition-colors"
      >
        Admin
      </Link>
      {segments.slice(1).map((segment, index) => {
        const isLast = index === segments.slice(1).length - 1;
        const href = "/admin/" + segments.slice(1, index + 2).join("/");

        return (
          <span key={segment} className="flex items-center gap-2">
            <span className="text-muted-foreground">/</span>
            {isLast ? (
              <span className="font-medium text-foreground capitalize">
                {segment}
              </span>
            ) : (
              <Link
                href={href}
                className="text-muted-foreground hover:text-foreground transition-colors capitalize"
              >
                {segment}
              </Link>
            )}
          </span>
        );
      })}
    </nav>
  );
}

function AdminSidebar() {
  const pathname = usePathname();

  return (
    <aside
      className="h-full w-64 bg-card/80 border-r border-border flex flex-col shrink-0"
      role="navigation"
      aria-label="Admin navigation"
    >
      {/* Header */}
      <div className="flex items-center gap-2 px-4 py-4 border-b border-border">
        <Shield className="h-5 w-5 text-primary" aria-hidden="true" />
        <h1 className="font-semibold text-foreground">Admin Panel</h1>
      </div>

      {/* Navigation */}
      <ScrollArea className="flex-1 px-3 py-4">
        <nav className="space-y-1" aria-label="Admin sections">
          {navItems.map((item) => {
            const isActive = pathname === item.href || pathname.startsWith(`${item.href}/`);

            return (
              <TooltipProvider key={item.href} delayDuration={0}>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Link
                      href={item.href}
                      className={cn(
                        "flex items-center gap-3 px-3 py-2 rounded-md text-sm transition-colors",
                        isActive
                          ? "bg-primary/10 text-primary font-medium"
                          : "text-foreground/80 hover:bg-muted/60 hover:text-foreground"
                      )}
                      aria-current={isActive ? "page" : undefined}
                    >
                      {item.icon}
                      <span>{item.label}</span>
                    </Link>
                  </TooltipTrigger>
                  <TooltipContent side="right">
                    <p>{item.label}</p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            );
          })}
        </nav>
      </ScrollArea>

      {/* Back to Chat */}
      <div className="p-3 border-t border-border">
        <TooltipProvider delayDuration={0}>
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                className="w-full justify-start gap-2 text-foreground/80 hover:text-foreground"
                asChild
              >
                <Link href="/chat">
                  <ArrowLeft className="h-4 w-4" aria-hidden="true" />
                  <span>Back to Chat</span>
                </Link>
              </Button>
            </TooltipTrigger>
            <TooltipContent side="right">
              <p>Return to chat interface</p>
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
      </div>
    </aside>
  );
}

export default function AdminLayout({ children }: AdminLayoutProps) {
  return (
    <div className="flex h-screen bg-background">
      {/* Left: Admin Sidebar */}
      <AdminSidebar />

      {/* Right: Main Content */}
      <main className="flex-1 flex flex-col overflow-hidden" role="main">
        {/* Header with Breadcrumb */}
        <header className="flex items-center gap-4 px-6 py-4 border-b border-border shrink-0">
          <Breadcrumb />
        </header>

        {/* Page Content */}
        <div className="flex-1 overflow-auto p-6">
          {children}
        </div>
      </main>
    </div>
  );
}
